//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeneMercha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagory
    {
        public Catagory()
        {
            this.Elections = new HashSet<Election>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Election> Elections { get; set; }
    }
}
