//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeneMercha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Election
    {
        public Election()
        {
            this.Candidates = new HashSet<Candidate>();
        }
    
        public int Id { get; set; }

        [DisplayName("Title")]
        [Required(ErrorMessage = "Please Enter Title Of Election.")]
        public string title { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "Please Enter Description about Election.")]
        public string description { get; set; }

        [DisplayName("Start Date")]
        [Required(ErrorMessage = "Please Enter Election Start Date")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> start_date { get; set; }

        [DisplayName("Stop Date")]
        [Required(ErrorMessage = "Please Enter Election Stop Date.")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> stop_date { get; set; }
        public Nullable<int> catagory_id { get; set; }
        
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual Catagory Catagory { get; set; }
        public string catagory;
    }
}

