//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeneMercha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int Id { get; set; }

        [DisplayName("First Name :")]
        [Required(ErrorMessage = "Please Enter First Name")]
        public string first_name { get; set; }

        [DisplayName("Last Name :")]
        [Required(ErrorMessage = "Please Enter Last Name")]
        public string last_name { get; set; }

        [DisplayName("user name :")]
        [Required(ErrorMessage = "Please Enter user name")]
        public string username { get; set; }

        [DisplayName("Password :")]
        [Required(ErrorMessage = "Please Enter Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Confirm Password :")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string Confirmpassword { get; set; }

        [DisplayName("Email Address :")]
        [Required(ErrorMessage = "Please Enter Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [DisplayName("User Address :")]
        [Required(ErrorMessage = "Please Enter Address")]
        public string address { get; set; }

        [DisplayName("Security Question :")]
        [Required(ErrorMessage = "Please Select Question")]
        public Nullable<int> question_id { get; set; }

        [DisplayName("Security Answer :")]
        [Required(ErrorMessage = "Please Enter Answer.")]
        public string answer { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
