//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeneMercha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> candidate_id { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual User User { get; set; }
    }
}
